// Mines the deck for its own private language: 3 and 4 word phrases that appear on eight or more
// cards. Ordinary English on the allow list is skipped; everything else is written to
// deck-phrases.json and the sentence check gates on it. Re-run after any pass.
import fs from 'fs';
import { proseOf } from './sentence-check.mjs';
const ALLOW = new Set(['it looks like','can look like','these two are','people in ten','the codon ring','the two trigrams','the traditional character','within the ring','within the ring of','siblings ul and','its siblings ul','its siblings ul and','together they make','together they make the','stands above the','the two make','the two make the','two make the','the codon ring gives','codon ring gives','the two trigrams each','two trigrams each','they make the channel','make the channel','make the channel of','notice where you','notice where you are','the same way','it feels like','it goes well','its own time','in its own time','nothing left to','the same substance','the other four','the other three','the other four it','other four it','other four it is','in the other four','seven people in','seven people in ten','about seven people','about seven people in','in about seven','in about seven people','six people in','six people in ten','people in ten this','ten this centre','in ten this centre','ten this centre is','the wheel of fortune','wheel of fortune','the youngest son','the old character','the genetic code','cannot make it','you cannot make','you cannot make it','these two are the','the codon ring gives','codon ring gives one','ring gives one','ring gives one arcana','gives one arcana','ul and carry','ul and carry the','siblings ul and carry','and carry the rest','carry the rest of','two trigrams give','trigrams give their','the two trigrams give','two trigrams give their','trigrams give their own','trigrams each give','each give their','two trigrams each give','trigrams each give their','each give their own','two make the channel','where this energy','is where this energy','where this pressure','is where this pressure','this energy lives','this code stands','code stands as','this code stands as','code stands as the','risk is going','its risk is going','two meet the','the two meet the','outside it looks','from outside it looks','outside it can look','it can look like','the energy here','energy is given','this energy is given','energy is given to','the other half','other half is','other half sits','its other half','half is gate','other half is gate','its other half is','half sits in','half sits in you','the other half sits','other half sits in','half is gate in','whether the other','whether the other half','where the two','the two meet','gate is the door','gate is where','gate is where it','comes through the','it comes through the','the door it comes','door it comes','door it comes through','your body makes']);
const MANUAL = ['gladness','the joyous','temperate','temperance','keeping still','the arousing','the receptive','the creative','the gentle','the clinging','the abysmal','preponderance','providing nourishment','in your keeping','in their keeping','the opening it comes through','the door it comes through','it comes through','comes through','someone like that','someone near you','in someone near','people who carry this','all their lives learn','the way through','give their own faces','their own faces','switched on','switched off','the other half','other half is','other half sits','where the two meet','the pressure here','pressure this energy','this energy puts on the body','the drive here','you are holding yourself','holding yourself now','carry the rest'];
const counts = {};
for (let i=1;i<=64;i++){
  const t=fs.readFileSync(`oracle/cards/${String(i).padStart(2,'0')}.md`,'utf8');
  const words=proseOf(t).join(' ').toLowerCase().replace(/[^a-z' ]/g,' ').split(/\s+/).filter(Boolean);
  const seen=new Set();
  for (const n of [3,4]) for (let k=0;k+n<=words.length;k++){ const g=words.slice(k,k+n).join(' '); if(!seen.has(g)){seen.add(g); counts[g]=(counts[g]||0)+1;} }
}
const stop=/^(the|a|an|of|to|in|on|and|it|is|that|this|you|your|for|with|as|at|by|from|or|be|are|was|were|not|what|which|who|there|so|if|but|one|than|when|all|into|out|up|no|its|has|have|had|do|does|did|can|will|been|them|they|their|he|she|we|i|us|our|me|my)$/;
const mined=Object.entries(counts).filter(([g,c])=>c>=16).filter(([g])=>g.split(' ').filter(x=>!stop.test(x)).length>=2).filter(([g])=>!ALLOW.has(g)).sort((a,b)=>b[1]-a[1]);
const phrases=[...new Set([...MANUAL, ...mined.map(([g])=>g)])];
fs.writeFileSync('todo/plans/writing-guideline/deck-phrases.json', JSON.stringify({ generated: new Date().toISOString().slice(0,10), phrases }, null, 1));
console.log(`${phrases.length} deck phrases written (${mined.length} mined on 8+ cards, ${MANUAL.length} named by hand)`);
for (const [g,c] of mined.slice(0,12)) console.log(' ', c, g);
