/**
 * The sphere body: deep stone surface, warm fresnel rim light, and the
 * cymatic ripple layer — each placed piece emits slow concentric rings of
 * light from its city; where rings from different pieces meet they sum, so
 * the surface pattern is generated by where the work rests.
 *
 * Ripple centres are passed as unit vectors in the sphere's local space, so
 * they rotate with the globe for free. Capped at MAX_RIPPLES; on low-tier
 * devices the ripple loop is skipped entirely (uRippleCount = 0).
 */

import { useFrame } from '@react-three/fiber';
import { useEffect, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { COLOR_BG, COLOR_BRONZE, COLOR_RIM, GLOBE_RADIUS, latLngToVec3, useRig } from './rig';

export const MAX_RIPPLES = 48;

const VERT = /* glsl */ `
  varying vec3 vNormal;
  varying vec3 vWorldNormal;
  varying vec3 vViewDir;
  void main() {
    vNormal = normal;
    vec4 worldPos = modelMatrix * vec4(position, 1.0);
    vWorldNormal = normalize(mat3(modelMatrix) * normal);
    vViewDir = normalize(cameraPosition - worldPos.xyz);
    gl_Position = projectionMatrix * viewMatrix * worldPos;
  }
`;

const FRAG = /* glsl */ `
  uniform vec3 uBase;
  uniform vec3 uRim;
  uniform vec3 uRipple;
  uniform float uTime;
  uniform float uBreath;
  uniform int uRippleCount;
  uniform vec3 uRippleCenters[${MAX_RIPPLES}];
  varying vec3 vNormal;        // local-space normal == ripple space
  varying vec3 vWorldNormal;
  varying vec3 vViewDir;

  void main() {
    // Deep stone base, a touch lighter toward the lit upper-left.
    float shade = 0.85 + 0.15 * dot(vWorldNormal, normalize(vec3(-0.4, 0.7, 0.6)));
    vec3 col = uBase * shade;

    // Warm fresnel rim — the limb catches a low bronze light, kept tight so
    // the face of the world stays deep stone rather than washing out.
    float fres = pow(1.0 - max(dot(vWorldNormal, vViewDir), 0.0), 3.4);
    col += uRim * fres * (0.55 + 0.2 * uBreath);

    // Cymatic ripples: angular distance from each placed piece drives a slow
    // ring; rings decay with distance and sum where they overlap.
    float ripple = 0.0;
    vec3 n = normalize(vNormal);
    for (int i = 0; i < ${MAX_RIPPLES}; i++) {
      if (i >= uRippleCount) break;
      float d = acos(clamp(dot(n, uRippleCenters[i]), -1.0, 1.0));
      float wave = sin(d * 40.0 - uTime * 1.1);
      float ring = smoothstep(0.25, 1.0, wave);
      ripple += ring * exp(-d * 7.0);
    }
    col += uRipple * min(ripple, 1.2) * 0.028;

    gl_FragColor = vec4(col, 1.0);
    #include <tonemapping_fragment>
    #include <colorspace_fragment>
  }
`;

export interface GlobeSphereProps {
  /** Placed-piece positions as [lat, lng] pairs (ripple sources). */
  rippleSources: ReadonlyArray<readonly [number, number]>;
}

export default function GlobeSphere({ rippleSources }: GlobeSphereProps) {
  const rig = useRig();

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        vertexShader: VERT,
        fragmentShader: FRAG,
        uniforms: {
          uBase: { value: COLOR_BG.clone().multiplyScalar(1.12) },
          uRim: { value: COLOR_RIM.clone() },
          uRipple: { value: COLOR_BRONZE.clone() },
          uTime: { value: 0 },
          uBreath: { value: 0 },
          uRippleCount: { value: 0 },
          uRippleCenters: {
            value: Array.from({ length: MAX_RIPPLES }, () => new THREE.Vector3(0, 0, 1)),
          },
        },
      }),
    [],
  );
  useEffect(() => () => material.dispose(), [material]);

  // Feed ripple centres (local space — they ride the spin group's rotation).
  useEffect(() => {
    const centers = material.uniforms.uRippleCenters.value as THREE.Vector3[];
    const count = rig.lowTier ? 0 : Math.min(rippleSources.length, MAX_RIPPLES);
    for (let i = 0; i < count; i++) {
      latLngToVec3(rippleSources[i][0], rippleSources[i][1], 1, centers[i]);
    }
    material.uniforms.uRippleCount.value = count;
  }, [material, rippleSources, rig.lowTier]);

  useFrame(({ clock }) => {
    const t = clock.elapsedTime;
    material.uniforms.uTime.value = t;
    // Same 3.5s breathing cycle the cobe globe used.
    material.uniforms.uBreath.value = Math.sin((t * Math.PI * 2) / 3.5);
  });

  return (
    <mesh material={material} renderOrder={0}>
      <sphereGeometry args={[GLOBE_RADIUS, 96, 96]} />
    </mesh>
  );
}
