/**
 * The engraved earth (build-order item 3: the engraved earth and the field).
 *
 * The sphere reads the baked hairline-earth texture (public/atlas/earth-hb.png,
 * generated by scripts/generate-earth-texture.mjs) as DATA, not a picture:
 *   R = land mask · G = coast hairline · B = waterline glow + echo ring
 * and composes the ruled earth in the fragment shader so it can be modulated at
 * runtime — the load-bearing move of this phase (todo/plans, "The planet
 * itself"). Composition, per the ratified mockup (variant hb, no graticule):
 *   ocean radial gradient  (OCEAN_* — the mockup sphere defs)
 *   + land lifted one shade (R, the I-b value)
 *   + coast tinted gold     (G, the 0.7px 0.55 line)
 *   + waterline             (B, the wide luminous strokes + carved echo)
 *   + standing light pools  (per placed light, additive-warm, weight-scaled)
 *   + coast catch-light     (inside a pool the engraving brightens to warm white)
 *
 * Pool centres are unit vectors in the sphere's local space, so they ride the
 * spin group's rotation for free (as the retired ripple layer did). Capped at
 * MAX_POOLS; over the cap the heaviest are kept and a warning names the drop.
 */

import { useFrame } from '@react-three/fiber';
import { useEffect, useMemo, useState } from 'react';
import * as THREE from 'three';
import {
  CATCH_WHITE,
  COAST_GOLD,
  EMBER_POOL,
  GLOBE_RADIUS,
  LAND_LIFT,
  LightPool,
  MAX_POOLS,
  OCEAN_CORE,
  OCEAN_EDGE,
  OCEAN_MID,
  POOL_CORE,
  latLngToVec3,
  useRig,
} from './rig';

const VERT = /* glsl */ `
  varying vec3 vNormal;
  varying vec3 vWorldNormal;
  varying vec3 vViewDir;
  void main() {
    vNormal = normal;
    vec4 worldPos = modelMatrix * vec4(position, 1.0);
    vWorldNormal = normalize(mat3(modelMatrix) * normal);
    vViewDir = normalize(cameraPosition - worldPos.xyz);
    gl_Position = projectionMatrix * viewMatrix * worldPos;
  }
`;

const FRAG = /* glsl */ `
  precision highp float;
  uniform sampler2D uMap;
  uniform vec3 uOceanCore;
  uniform vec3 uOceanMid;
  uniform vec3 uOceanEdge;
  uniform vec3 uLandLift;
  uniform vec3 uCoast;
  uniform vec3 uPoolCore;
  uniform vec3 uEmberPool;
  uniform vec3 uCatch;
  uniform float uBreath;
  uniform int uPoolCount;
  uniform vec3 uPoolCenters[${MAX_POOLS}];
  uniform float uPoolWeights[${MAX_POOLS}]; // >0 lit (weight), <0 ember
  varying vec3 vNormal;        // local-space normal == texture + pool space
  varying vec3 vWorldNormal;
  varying vec3 vViewDir;

  const float PI = 3.141592653589793;

  void main() {
    vec3 n = normalize(vNormal);

    // Equirectangular lookup from the surface normal, in the exact convention
    // latLngToVec3 uses (x=cosLat*sinLng, y=sinLat, z=cosLat*cosLng), so the
    // texture aligns with the markers. The texture is loaded flipY, so v=1 is
    // the north pole — matching lat +90.
    float lat = asin(clamp(n.y, -1.0, 1.0));
    float lng = atan(n.x, n.z);
    vec2 uv = vec2(lng / (2.0 * PI) + 0.5, lat / PI + 0.5);
    vec4 tex = texture2D(uMap, uv);
    float land = smoothstep(0.42, 0.58, tex.r);
    float coastLine = tex.g;
    float waterline = tex.b;

    // Ocean radial gradient: brightest at the face, falling to the limb, with a
    // gentle upper-left lift for the low stage light (the mockup's cx38% cy34%).
    float facing = clamp(dot(vWorldNormal, vViewDir), 0.0, 1.0);
    vec3 ocean = mix(uOceanEdge, uOceanMid, smoothstep(0.0, 0.55, facing));
    ocean = mix(ocean, uOceanCore, smoothstep(0.55, 1.0, facing));
    float lit = 0.5 + 0.5 * dot(vWorldNormal, normalize(vec3(-0.4, 0.7, 0.6)));
    ocean *= (0.9 + 0.18 * lit);

    // Land: the ocean tone lifted one shade (the I-b value). Both share the
    // radial falloff so the earth reads as one engraved plate.
    vec3 col = ocean + uLandLift * land;

    // Standing light pools + the coast catch-light term. Chord distance (no
    // acos) keeps the 64-pool loop cheap; a gaussian on it reads as radiance.
    // Both terms accumulate as SCALARS across every pool, so a cluster's
    // gaussians add up — then a soft-knee compression (below) folds the sum
    // back toward a bounded warm gold, so clustered lights read as a greater
    // warmth, never as overexposure (the "less is more" ruling).
    float poolAccum = 0.0;
    float catchAccum = 0.0;
    float breath = 0.94 + 0.06 * uBreath;
    for (int i = 0; i < ${MAX_POOLS}; i++) {
      if (i >= uPoolCount) break;
      float w = uPoolWeights[i];
      float c = dot(n, uPoolCenters[i]);
      float d2 = max(0.0, 2.0 * (1.0 - c)); // squared chord ~ angular^2
      if (w < 0.0) {
        // Ember: a very small, dim pool, no catch-light. Added straight in;
        // embers are faint and never cluster into a bloom.
        float s2 = 0.0016;
        float e = exp(-d2 / (2.0 * s2)) * 0.5;
        col += uEmberPool * e;
      } else {
        // A lit dream: pool radius grows with the pieces sharing the point, so
        // where dreams cluster the pool is plainly larger (Lisbon, three lights
        // on one point). The amplitude also grows with the cluster, but only
        // into the accumulator: the compression downstream keeps the sum warm,
        // not white.
        float lw = log2(w + 1.0);
        float sigma = 0.079 * (1.0 + 0.30 * lw);
        float s2 = sigma * sigma;
        float e = exp(-d2 / (2.0 * s2));
        poolAccum += e * (0.5 + 0.14 * lw) * breath;
        // The catch-light gathers tighter than the pool, so the engraving
        // brightens right around the dream, strongest where dreams cluster.
        float cs2 = s2 * 0.4;
        catchAccum += exp(-d2 / (2.0 * cs2)) * min(w, 4.0);
      }
    }

    // Soft-knee compression, x/(1+x): maps the unbounded accumulators into
    // [0,1). A lone light lands near ~0.3, a dense cluster near ~0.7 — clearly
    // warmer, but the ceiling is uPoolCore (a warm gold, #eec387), never white.
    // The land engraving underneath is never swallowed because the pool tops
    // out well short of saturation and the coast is drawn OVER it below.
    float poolC = poolAccum / (1.0 + poolAccum);
    float catchC = catchAccum / (1.0 + catchAccum);
    col += uPoolCore * poolC * 0.85;

    // Coast hairline, tinted gold, brightening toward warm white inside a pool
    // (the mockup's masked catch-light pass). Kept a quiet hairline away from
    // the dreams and lifting within a pool — scaled by the compressed catch so
    // a dream lights up the drawing of the earth around it without shouting.
    vec3 coastCol = mix(uCoast, uCatch, catchC);
    col += coastCol * coastLine * (0.32 + catchC * 0.72);

    // Waterline: the luminous halo + carved echo, gold, kept a whisper and
    // gathering a little more where the coast catches the light.
    col += uCoast * waterline * 0.11 * (1.0 + catchC * 0.7);

    gl_FragColor = vec4(col, 1.0);
    #include <tonemapping_fragment>
    #include <colorspace_fragment>
  }
`;

export interface GlobeSphereProps {
  /** Standing pools cast by the placed lights and dim embers. */
  pools: ReadonlyArray<LightPool>;
}

function textureUrl(lowTier: boolean): string {
  return lowTier ? '/atlas/earth-hb-2k.png' : '/atlas/earth-hb.png';
}

export default function GlobeSphere({ pools }: GlobeSphereProps) {
  const rig = useRig();
  const [map, setMap] = useState<THREE.Texture | null>(null);

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        vertexShader: VERT,
        fragmentShader: FRAG,
        uniforms: {
          uMap: { value: null },
          uOceanCore: { value: OCEAN_CORE.clone() },
          uOceanMid: { value: OCEAN_MID.clone() },
          uOceanEdge: { value: OCEAN_EDGE.clone() },
          uLandLift: { value: LAND_LIFT.clone() },
          uCoast: { value: COAST_GOLD.clone() },
          uPoolCore: { value: POOL_CORE.clone() },
          uEmberPool: { value: EMBER_POOL.clone() },
          uCatch: { value: CATCH_WHITE.clone() },
          uBreath: { value: 0 },
          uPoolCount: { value: 0 },
          uPoolCenters: {
            value: Array.from({ length: MAX_POOLS }, () => new THREE.Vector3(0, 0, 1)),
          },
          uPoolWeights: { value: new Float32Array(MAX_POOLS) },
        },
      }),
    [],
  );
  useEffect(() => () => material.dispose(), [material]);

  // Load the baked hairline-earth texture (lower-res on low-tier devices).
  useEffect(() => {
    let alive = true;
    const loader = new THREE.TextureLoader();
    loader.load(textureUrl(rig.lowTier), (t) => {
      if (!alive) {
        t.dispose();
        return;
      }
      t.wrapS = THREE.RepeatWrapping; // longitude wraps; no seam at the date line
      t.wrapT = THREE.ClampToEdgeWrapping;
      t.minFilter = THREE.LinearMipmapLinearFilter;
      t.magFilter = THREE.LinearFilter;
      t.anisotropy = 8;
      t.needsUpdate = true;
      material.uniforms.uMap.value = t;
      setMap(t);
    });
    return () => {
      alive = false;
    };
  }, [material, rig.lowTier]);
  useEffect(() => () => map?.dispose(), [map]);

  // Feed pool centres (local space) + weights. Cap at MAX_POOLS, keeping the
  // heaviest; name any drop rather than slicing silently.
  useEffect(() => {
    const centers = material.uniforms.uPoolCenters.value as THREE.Vector3[];
    const weights = material.uniforms.uPoolWeights.value as Float32Array;
    let list = pools;
    if (list.length > MAX_POOLS) {
      console.warn(
        `[Atlas] Light-pool capacity ${MAX_POOLS} exceeded: keeping the ${MAX_POOLS} heaviest of ${list.length} pools.`,
      );
      list = [...pools].sort((a, b) => b.weight - a.weight).slice(0, MAX_POOLS);
    }
    const count = Math.min(list.length, MAX_POOLS);
    for (let i = 0; i < count; i++) {
      latLngToVec3(list[i].lat, list[i].lng, 1, centers[i]);
      // Sign encodes kind: positive weight = lit pool, negative = dim ember.
      weights[i] = list[i].ember ? -1 : Math.max(1, list[i].weight);
    }
    material.uniforms.uPoolCount.value = count;
    material.uniforms.uPoolWeights.value = weights;
  }, [material, pools]);

  useFrame(({ clock }) => {
    const t = clock.elapsedTime;
    if (rig.reducedMotion) {
      material.uniforms.uBreath.value = 0;
      return;
    }
    // The same 3.5s breathing cycle the lights carry, so the pools breathe with
    // them rather than against them.
    material.uniforms.uBreath.value = Math.sin((t * Math.PI * 2) / 3.5);
  });

  return (
    <mesh material={material} renderOrder={0}>
      <sphereGeometry args={[GLOBE_RADIUS, 96, 96]} />
    </mesh>
  );
}
