import { authorized, bodyJson, buildInvocationArtifact, json, nextVersion, numberParam, parseInvocationMarkdown, validId, type InvocationContext } from '../_shared';
export async function onRequestGet(context: InvocationContext) {
  const access = await authorized(context); if (access instanceof Response) return access; const number = numberParam(context.params.number); if (!number) return json({ error: 'invalid hexagram' }, 400);
  const rows = await access.db.prepare('SELECT * FROM oracle_invocation_versions WHERE hexagram_number=?1 ORDER BY version_number DESC').bind(number).all<Record<string, unknown>>();
  return json(rows.results.map((row) => ({ id: row.id, hexagramNumber: row.hexagram_number, versionNumber: row.version_number, title: row.title, markdownBody: row.markdown_body, artifactKey: row.artifact_key, authorUserId: row.author_user_id, createdAt: row.created_at })));
}
export async function onRequestPost(context: InvocationContext) {
  const access = await authorized(context); if (access instanceof Response) return access; const number = numberParam(context.params.number); if (!number) return json({ error: 'invalid hexagram' }, 400); if (!context.env.ORACLE_PRIVATE) return json({ error: 'ORACLE_PRIVATE binding unavailable' }, 503);
  const raw = await bodyJson(context.request); if (raw instanceof Response) return raw; if (raw.action !== 'rollback' || !validId(raw.versionId)) return json({ error: 'invalid rollback' }, 400);
  const source = await access.db.prepare('SELECT * FROM oracle_invocation_versions WHERE id=?1 AND hexagram_number=?2').bind(raw.versionId, number).first<Record<string, unknown>>(); if (!source) return json({ error: 'version not found' }, 404);
  const parsed = parseInvocationMarkdown(String(source.markdown_body)); const version = await nextVersion(access.db, number); const now = new Date().toISOString(); const id = crypto.randomUUID(); const artifact = buildInvocationArtifact({ hexagramNumber: number, title: String(source.title), versionNumber: version, artifactId: id, author: access.auth.userId, createdAt: now, updatedAt: now, body: String(source.markdown_body) });
  try { await context.env.ORACLE_PRIVATE.put(artifact.key, artifact.contents, { httpMetadata: { contentType: 'text/markdown; charset=utf-8' } }); await access.db.batch([access.db.prepare('INSERT INTO oracle_invocation_versions (id,hexagram_number,draft_id,version_number,title,markdown_body,rendered_json,artifact_key,author_user_id,idempotency_key,created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,NULL,?10)').bind(id, number, source.draft_id, version, source.title, source.markdown_body, JSON.stringify(parsed.blocks), artifact.key, access.auth.userId, now), access.db.prepare('INSERT INTO oracle_invocation_live (hexagram_number,version_id,updated_at) VALUES (?1,?2,?3) ON CONFLICT(hexagram_number) DO UPDATE SET version_id=excluded.version_id,updated_at=excluded.updated_at').bind(number, id, now)]); } catch { await context.env.ORACLE_PRIVATE.delete(artifact.key).catch(() => undefined); return json({ error: 'rollback failed' }, 503); }
  return json({ id, hexagramNumber: number, versionNumber: version, title: source.title, markdownBody: source.markdown_body, artifactKey: artifact.key, authorUserId: access.auth.userId, createdAt: now });
}
